module.exports = {
  theme: {
    extend: {
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
        roboto: ['Roboto', 'sans-serif'],
        montserrat: ['Montserrat', 'sans-serif'],
        nunito: ['Nunito', 'sans-serif'],
        lato: ['Lato', 'sans-serif'],
        worksans: ['Work Sans', 'sans-serif'],
        opensans: ['Open Sans', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
        sora: ['Sora', 'sans-serif'],
        urbanist: ['Urbanist', 'sans-serif'],
        plusjakarta: ['Plus Jakarta Sans', 'sans-serif'],
        dmsans: ['DM Sans', 'sans-serif'],
        spacegrotesk: ['Space Grotesk', 'sans-serif'],
        playfair: ['Playfair Display', 'serif'],
        merriweather: ['Merriweather', 'serif'],
        lora: ['Lora', 'serif'],
        cormorant: ['Cormorant Garamond', 'serif'],
        libre: ['Libre Baskerville', 'serif'],
        bebas: ['Bebas Neue', 'sans-serif'],
        oswald: ['Oswald', 'sans-serif'],
        abril: ['Abril Fatface', 'serif'],
        anton: ['Anton', 'sans-serif'],
        righteous: ['Righteous', 'cursive'],
        pacifico: ['Pacifico', 'cursive'],
        firacode: ['Fira Code', 'monospace'],
        jetbrains: ['JetBrains Mono', 'monospace'],
        sourcecode: ['Source Code Pro', 'monospace'],
        robotomono: ['Roboto Mono', 'monospace'],
        notojp: ['Noto Sans JP', 'sans-serif'],
        notoserifjp: ['Noto Serif JP', 'serif'],
        mplus: ['M PLUS Rounded 1c', 'sans-serif'],
      },
    },
  },
};